platform :ios, '7.0'
target 'Rebound' do
  
  pod 'iRate'
  
  pod 'AdToApp/Interstitial'
  pod 'AdToApp/Image'
  pod 'AdToApp/Video'
#  pod 'AdToApp/Reward'
  pod 'AdToApp/Banner'
  pod 'AdToApp/AdColony'
  pod 'AdToApp/AmazonAd'
  pod 'AdToApp/Applovin'
  pod 'AdToApp/AdMob'
  pod 'AdToApp/InMobi'
  pod 'AdToApp/MyTarget'
  pod 'AdToApp/Smaato'
  pod 'AdToApp/StartApp'
  pod 'AdToApp/TapSense'
  pod 'AdToApp/Unity'
  pod 'AdToApp/Vungle'
  pod 'AdToApp/Supersonic'
  pod 'AdToApp/NativeX'
  pod 'AdToApp/Avocarrot'
  pod 'AdToApp/Instreamatic'
  pod 'AdToApp/Revmob'
  pod 'AdToApp/Flurry'
  pod 'AdToApp/Inhouse'
  pod 'AdToApp/Yandex'
  
end
